### ISSUE TITLE
No module named 'train_class'

### ISSUE THREAD

**Issue by LiuJia68** [naszilla/nas-encodings#1]
When search space=='darts',
    from train_class import Train
ModuleNotFoundError: No module named 'train_class'

**Comment by crwhite14** [comment]
Thanks for pointing out this mistake. We meant to add to the readme a bit more steps to run experiments on the DARTS search space.

- Download our fork of the DARTS repo: `https://github.com/naszilla/darts`
- If you don't put the repo in your home directory, i.e., `~/darts`, then you might need to update line 7 of `nas-encodings/darts/arch.py` and line 8 of `nas-encodings/train_arch_runner.py` with the correct path.

I will update the readme to explain these steps.
